name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust according to your default branch
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Your Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Your Docker Hub password

      - name: Build Docker Images
        run: |
          docker-compose build  # Build your images defined in docker-compose.yml

      - name: Push Docker Images
        run: |
          # docker-compose push  # Push the built images to Docker Hub

      - name: Run Tests
        run: |
          docker-compose up -d  # Start the services in detached mode
          # Insert any tests you want to run here, e.g.:
          # docker-compose exec locomotive your_test_command
          docker-compose down  # Stop and remove the containers
